"""empty message

Revision ID: 1a7197dcda95
Revises: b08d30410d43
Create Date: 2025-08-07 01:52:05.912466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a7197dcda95'
down_revision = 'b08d30410d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingresos',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('id_categoria_de_ingreso', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_ingreso'], ['categorias_de_ingresos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingreso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingreso',
    sa.Column('id_cuenta', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_categoria_de_ingreso', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('importe', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notas', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_visualizacion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fecha_de_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_usuario', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_ingreso'], ['categorias_de_ingresos.id'], name='ingreso_id_categoria_de_ingreso_fkey'),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], name='ingreso_id_cuenta_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], name='ingreso_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingreso_pkey')
    )
    op.drop_table('ingresos')
    # ### end Alembic commands ###
