"""empty message

Revision ID: 37eacf7badc6
Revises: e44ad5aac205
Create Date: 2025-08-09 13:23:37.595000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eacf7badc6'
down_revision = 'e44ad5aac205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena_api', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('contrasena_api')

    # ### end Alembic commands ###
