"""empty message

Revision ID: 5ed360c9202a
Revises: fcffc4222dd9
Create Date: 2025-08-08 12:54:12.476038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed360c9202a'
down_revision = 'fcffc4222dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios_apple_pay', schema=None) as batch_op:
        batch_op.alter_column('id_categoria_de_gasto',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('negocios_apple_pay', schema=None) as batch_op:
        batch_op.alter_column('id_categoria_de_gasto',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
