"""empty message

Revision ID: a48c3808cfcf
Revises: 
Create Date: 2025-08-07 01:34:12.806554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48c3808cfcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tabla', sa.String(length=255), nullable=False),
    sa.Column('id_registro', sa.String(length=255), nullable=False),
    sa.Column('usuario', sa.String(length=255), nullable=False),
    sa.Column('accion', sa.String(length=1000), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=1000), nullable=False),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('categorias_de_gastos',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_de_ingresos',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('monto_credito', sa.Integer(), nullable=True),
    sa.Column('dia_de_corte', sa.Integer(), nullable=True),
    sa.Column('dia_de_pago', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('id_categoria_de_gasto', sa.UUID(), nullable=False),
    sa.Column('gasto_compartido', sa.String(length=255), nullable=True),
    sa.Column('categoria_apple_pay', sa.String(length=255), nullable=True),
    sa.Column('negocio', sa.String(length=255), nullable=True),
    sa.Column('pagos_mensuales', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_gasto'], ['categorias_de_gastos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos_recurrentes',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('id_categoria_de_gasto', sa.UUID(), nullable=False),
    sa.Column('gasto_compartido', sa.String(length=50), nullable=True),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_gasto'], ['categorias_de_gastos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('id_categoria_de_ingreso', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_ingreso'], ['categorias_de_ingresos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos_recurrentes',
    sa.Column('id_cuenta', sa.UUID(), nullable=False),
    sa.Column('id_categoria_de_ingreso', sa.UUID(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_ingreso'], ['categorias_de_ingresos.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transferencias',
    sa.Column('id_cuenta_entrada', sa.UUID(), nullable=False),
    sa.Column('id_cuenta_salida', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_cuenta_entrada'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_cuenta_salida'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencias')
    op.drop_table('ingresos_recurrentes')
    op.drop_table('ingreso')
    op.drop_table('gastos_recurrentes')
    op.drop_table('gastos')
    op.drop_table('cuentas')
    op.drop_table('categorias_de_ingresos')
    op.drop_table('categorias_de_gastos')
    op.drop_table('usuarios')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###
