"""empty message

Revision ID: bb562bae2eb9
Revises: 1a7197dcda95
Create Date: 2025-08-07 22:57:18.470983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb562bae2eb9'
down_revision = '1a7197dcda95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
