"""empty message

Revision ID: c58f5c44102c
Revises: 37eacf7badc6
Create Date: 2025-08-10 00:51:17.131542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58f5c44102c'
down_revision = '37eacf7badc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_de_reportes',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_categoria_de_reporte', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('ruta_sql', sa.String(length=50), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_reporte'], ['categorias_de_reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes')
    op.drop_table('categorias_de_reportes')
    # ### end Alembic commands ###
