"""empty message

Revision ID: d1f9aaf8ad8b
Revises: bb562bae2eb9
Create Date: 2025-08-08 11:47:50.455631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f9aaf8ad8b'
down_revision = 'bb562bae2eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios_apple_pay',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_categoria_de_gasto', sa.UUID(), nullable=False),
    sa.Column('estatus', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_visualizacion', sa.Integer(), nullable=True),
    sa.Column('fecha_de_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria_de_gasto'], ['categorias_de_gastos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_apple_pay', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuentas', schema=None) as batch_op:
        batch_op.drop_column('nombre_apple_pay')

    op.drop_table('negocios_apple_pay')
    # ### end Alembic commands ###
