"""empty message

Revision ID: e3ba41c48802
Revises: c58f5c44102c
Create Date: 2025-08-10 00:54:42.420098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ba41c48802'
down_revision = 'c58f5c44102c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_de_reportes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'])

    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    with op.batch_alter_table('categorias_de_reportes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
