"""empty message

Revision ID: e44ad5aac205
Revises: 5ed360c9202a
Create Date: 2025-08-09 13:06:30.021960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44ad5aac205'
down_revision = '5ed360c9202a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_conectado', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario_conectado'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_usuario_conectado')

    # ### end Alembic commands ###
