"""empty message

Revision ID: fcffc4222dd9
Revises: d1f9aaf8ad8b
Create Date: 2025-08-08 12:39:02.322615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcffc4222dd9'
down_revision = 'd1f9aaf8ad8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_negocio_apple_pay', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'negocios_apple_pay', ['id_negocio_apple_pay'], ['id'])
        batch_op.drop_column('negocio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negocio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_negocio_apple_pay')

    # ### end Alembic commands ###
