name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Zip application files
      run: zip -r application.zip .

    - name: Upload to S3
      env:
        S3_BUCKET: ${{ vars.S3_BUCKET }}
      run: aws s3 cp application.zip s3://$S3_BUCKET/application.zip

    - name: Deploy to Elastic Beanstalk
      env:
        APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
        ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME }}
        S3_BUCKET: ${{ vars.S3_BUCKET }}
      run: |
        aws elasticbeanstalk create-application-version --application-name "$APPLICATION_NAME" --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=application.zip
        aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA